export enum HorseBreed {
    Andalou = 'Andalou',
    Ane = 'Ane',
    Anglo_arabe = 'Anglo arabe',
    Appaloosa = 'Appaloosa',
    Autre = 'Autre',
    Barbe = 'Barbe',
    Camarguais = 'Camarguais',
    Double_poney = 'Double poney',
    Frison = 'Frison',
    Lusitanien = 'Lusitanien',
    Merens = 'Merens',
    Mule = 'Mule',
    Palomino = 'Palomino',
    Poney = 'Poney',
    Pur_sang_arabe = 'Pur sang arabe',
    Quarter_Horse = 'Quarter Horse',
    Race_indéfinie = 'Race indéfinie',
    Selle_Français = 'Selle Français',
    Shetland = 'Shetland',
    Trotteur = 'Trotteur',
    Type_Selle = 'Type Selle',
    Type_Trait = 'Type Trait'

}